# Generated by Django 3.0.4 on 2020-08-12 23:44

from django.db import migrations


def populate_model_year(apps, schema_editor):
    Trim = apps.get_model('vehicles', 'Trim')
    ModelYear = apps.get_model('vehicles', 'ModelYear')

    for trim in Trim.objects.all():
        try:
            model_year = ModelYear.objects.get(model=trim.model, year=trim.year)
        except ModelYear.DoesNotExist:
            model_year = ModelYear(model=trim.model, year=trim.year)
            model_year.save()
        trim.model_year = model_year
        trim.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_add_model_year_model'),
    ]

    operations = [
        migrations.RunPython(populate_model_year),
    ]
