# Generated by Django 3.0.4 on 2020-08-12 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_populate_model_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trim',
            name='model',
        ),
        migrations.RemoveField(
            model_name='trim',
            name='year',
        ),
        migrations.AlterField(
            model_name='trim',
            name='model_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='vehicles.ModelYear'),
        ),
    ]
