# Generated by Django 3.0.4 on 2020-08-16 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_remove_trim_model_and_year_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='modelyear',
            name='manufacturer_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='modelyear',
            name='image_attribution_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelyear',
            name='image_attribution_author_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='modelyear',
            name='image_attribution_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelyear',
            name='image_attribution_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='modelyear',
            name='image_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='modelyear',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='modelyear',
            name='image_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.MediaLicense'),
        ),
    ]
